---
- hosts: iojs-build-ubuntu1604
  remote_user: root
  gather_facts: False

  tasks:
    - name: Check for python
      raw: which python
      register: python_exists
      failed_when: python_exists.rc > 1

    - name: Bootstrap for the apt package
      raw: apt install -y python-minimal aptitude
      tags: bootstrap
      when: python_exists.rc == 1

- hosts: iojs-build-ubuntu1604
  remote_user: root
  gather_facts: True

  tasks:
    - include_vars: ansible-vars.yaml
      tags: vars

    - name: General | APT Update and upgrade
      apt: update_cache=yes upgrade=full
      tags: general

    - name: General | Install required packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items: packages
      tags: general

    - name: User | Add {{ server_user }} user
      user: name="{{ server_user }}" shell=/bin/bash
      tags: user


    - name: Jenkins | Download Jenkins slave.jar
      get_url: url=https://ci.nodejs.org/jnlpJars/slave.jar dest=/home/{{ server_user }}/slave.jar
      tags: jenkins

    - name: Init | Generate and copy init script
      template: src=./resources/jenkins.service.j2 dest=/lib/systemd/system/jenkins.service
      tags: init

    - name: Init | Start Jenkins
      service: name=jenkins state=started enabled=yes
      tags: init
